% Perform genetic operations (crossover and mutation) on the individuals in the mating pool
%
% INPUT: 
% 'pop' is the population to be evaluated [t+1 x n+4 x n_individuals]
% 'offspring' is the population of offspring generated by genetic operations [t+1 x n+4 x n_individuals]
% 'fit_array_P' is [n_individuals x 4] containing the fitness of each individual in the population and the index of the individual in the array 'pop'
% 'fit_array_O' is [n_individuals x 4] containing the fitness of each individual in the population and the index of the individual in the array 'offspring'
%
% OUTPUT: 
% 'nextGenPop' is the population of the next generation [t+1 x n+4 x n_individuals]
% 'fit_array_NGP' is [n_individuals x 4] containing the fitness of each individual in the next generation population and the index of the individual in the array 'nextGenPop'
function [nextGenPop, fit_array_NGP] = survivor(pop, offspring, fit_array_P, fit_array_O)
    
    global op;  % optimization problem
    global gas; % genetic algorithm settings
    
    switch gas.survival_method
        case 'non-elitist'
            nextGenPop = offspring;
            fit_array_NGP = fit_array_O;    % not much more to do here...
        case 'elitist_full'
            [nextGenPop, fit_array_NGP] = elitistSurvivalFull(pop, offspring, fit_array_P, fit_array_O);
        case 'elitist_alpha'
            [nextGenPop, fit_array_NGP] = elitistSurvivalAlpha(pop, offspring, fit_array_P, fit_array_O);
        otherwise
            error('Unexpected Survival Method.');
    end
    
end

%--------------ELITIST SURVIVAL, (MU+LAMBDA)-SCHEME --------------

%IMPORTANT: first merge both populations 'pop' and 'offspring', then it recalculate their rank (rank only makes sense within a population)
function [nextGenPop_final, fit_array_NGP] = elitistSurvivalFull(pop, offspring, fit_array_P, fit_array_O)
    global op;  % optimization problem
    global gas; % genetic algorithm settings
     
    nextGenPop = zeros(size(op.targets,1)+1,op.n_nodes+gas.extra_genes,gas.n_individuals*2);    % declare a static array of chromosomes filled with zeros
    fit_array_NGP = zeros(gas.n_individuals*2,length(fieldnames(gas.fitIdx)));                  % array containing fitness for each individual of the new population
    
    nextGenPop(:,:,1:gas.n_individuals) = pop;
    nextGenPop(:,:,gas.n_individuals+1:gas.n_individuals*2) = offspring;
    
    fit_array_O(:,gas.fitIdx.id) = fit_array_O(:,gas.fitIdx.id) + gas.n_individuals;
    
    fit_array_NGP(1:gas.n_individuals,:) = fit_array_P;
    fit_array_NGP(gas.n_individuals+1:gas.n_individuals*2,:) = fit_array_O;
    
    [fit_array_NGP] = rankingEvaluation(fit_array_NGP);
    fit_array_NGP(gas.n_individuals+1:gas.n_individuals*2,:) = [];
    
    
    nextGenPop_final = zeros(size(op.targets,1)+1,op.n_nodes+gas.extra_genes,gas.n_individuals);
    for i=1:gas.n_individuals 
        index = fit_array_NGP(i,gas.fitIdx.id);
        nextGenPop_final(:,:,i) = nextGenPop(:,:,index);
        fit_array_NGP(i,gas.fitIdx.id) = i;
    end
end

%--------------ELITIST SURVIVAL, (ALPHA)-SCHEME --------------

%IMPORTANT: first merge both populations 'pop' and 'offspring', then it recalculate their rank (rank only makes sense within a population)
function [nextGenPop, fit_array_NGP] = elitistSurvivalAlpha(pop, offspring, fit_array_P, fit_array_O)
    global op;  % optimization problem
    global gas; % genetic algorithm settings
    
    n_elites = fix(gas.survival_alpha*gas.n_individuals/100);
    n_off = gas.n_individuals - n_elites;
     
    nextGenPop = zeros(size(op.targets,1)+1,op.n_nodes+gas.extra_genes,gas.n_individuals);    % declare a static array of chromosomes filled with zeros
    fit_array_NGP = zeros(gas.n_individuals,length(fieldnames(gas.fitIdx)));                  % array containing fitness for each individual of the new population
    
    fit_array_O(:,gas.fitIdx.id) = fit_array_O(:,gas.fitIdx.id) + gas.n_individuals;            % new id for offspring
    
    fit_array_NGP(1:n_elites,:) = fit_array_P(1:n_elites,:);
    fit_array_NGP(n_elites+1:n_elites+n_off,:) = fit_array_O(1:n_off,:);
    
    [fit_array_NGP] = rankingEvaluation(fit_array_NGP);
    
    
    
    for i=1:gas.n_individuals 
        index = fit_array_NGP(i,gas.fitIdx.id);
        if index <= gas.n_individuals 
            nextGenPop(:,:,i) = pop(:,:,index);
        else
            index = index - gas.n_individuals;
            nextGenPop(:,:,i) = offspring(:,:,index);
        end
        fit_array_NGP(i,gas.fitIdx.id) = i;
    end
end

%--------------DYNAMIC SURVIVAL, ALPHA-SCHEME --------------
% IMPORTANT: it is not necessary to recalculate the rank as in the previous method, simply take the best alpha% from 'pop' and the best (1-alpha)%
% from 'offspring'. Useful if alpha changes dynamically as the generations proceed (starting with alpha = 0%) to gradually introduce elites in the new population
function [nextGenPop, fit_array_NGP] = dynamicSurvival(pop, offspring, fit_array_P, fit_array_O, alpha)
    global op;  % optimization problem
    global gas; % genetic algorithm settings
    error('This Survival Method is not implemented yet.');
end

